// Copyright Voxel Plugin SAS. All Rights Reserved.

#include "Navigation/VoxelNavigationInvoker.h"
#include "VoxelDependency.h"
#include "VoxelTaskContext.h"
#include "VoxelInvalidationCallstack.h"
#include "SceneView.h"
#include "SceneManagement.h"
#include "PrimitiveSceneProxy.h"

VOXEL_CONSOLE_VARIABLE(
	VOXEL_API, bool, GVoxelShowNavigationInvokers, false,
	"voxel.navigation.ShowInvokers",
	"Show the position of navigation invokers");

VOXEL_CONSOLE_WORLD_COMMAND(
	"voxel.navigation.LogInvokers",
	"Log the position of navigation invokers")
{
	FVoxelNavigationInvokerManager::Get(World)->LogInvokers();
}

///////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////

FVoxelNavigationInvokerView::FVoxelNavigationInvokerView(
	const int32 ChunkSize,
	const FTransform& LocalToWorld)
	: ChunkSize(ChunkSize)
	, LocalToWorld(LocalToWorld)
	, Dependency(FVoxelDependency::Create("FVoxelNavigationInvokerView"))
{
	ensure(ChunkSize > 0);
}

TVoxelFuture<const TVoxelSet<FIntVector>> FVoxelNavigationInvokerView::GetChunks(FVoxelDependencyCollector& DependencyCollector) const
{
	DependencyCollector.AddDependency(*Dependency);

	VOXEL_SCOPE_LOCK(CriticalSection);

	if (!Chunks_RequiresLock)
	{
		// Async to avoid recursive locks
		return Future.Then_AsyncThread(MakeStrongPtrLambda(this, [this]
		{
			VOXEL_SCOPE_LOCK(CriticalSection);
			return Chunks_RequiresLock.ToSharedRef();
		}));
	}

	return Chunks_RequiresLock.ToSharedRef();
}

void FVoxelNavigationInvokerView::Tick(const TVoxelSet<TObjectPtr<UVoxelNavigationInvokerComponent>>& InvokerComponents)
{
	VOXEL_FUNCTION_COUNTER();

	if (!Future.IsComplete())
	{
		return;
	}

	VOXEL_SCOPE_COUNTER_FORMAT("InvokerComponents.Num() = %d", InvokerComponents.Num());

	TVoxelArray<FSphere> Invokers;
	Invokers.Reserve(InvokerComponents.Num());

#if !UE_BUILD_SHIPPING
	TVoxelArray<TVoxelObjectPtr<const UVoxelNavigationInvokerComponent>> NewInvokerComponents;
	NewInvokerComponents.Reserve(InvokerComponents.Num());
#endif

	for (const UVoxelNavigationInvokerComponent* InvokerComponent : InvokerComponents)
	{
		if (!ensure(InvokerComponent) ||
			!InvokerComponent->bEnabled)
		{
			continue;
		}

#if !UE_BUILD_SHIPPING
		NewInvokerComponents.Add(InvokerComponent);
#endif

		Invokers.Add(FSphere
		{
			InvokerComponent->GetComponentLocation(),
			InvokerComponent->Radius
		});
	}

	if (Invokers == LastInvokers)
	{
		VOXEL_SCOPE_LOCK(CriticalSection);
		if (!Chunks_RequiresLock)
		{
			Chunks_RequiresLock = MakeShared<TVoxelSet<FIntVector>>();
		}
		return;
	}

	FString ComponentChanges = "FVoxelNavigationInvokerView changed:";
#if VOXEL_INVALIDATION_TRACKING
	if (NewInvokerComponents == LastInvokerComponents)
	{
		check(Invokers.Num() == LastInvokers.Num());

		for (int32 Index = 0; Index < LastInvokers.Num(); Index++)
		{
			if (LastInvokers[Index] == Invokers[Index])
			{
				continue;
			}

			const UVoxelNavigationInvokerComponent* InvokerComponent = NewInvokerComponents[Index].Resolve();
			if (!ensureVoxelSlow(InvokerComponent))
			{
				continue;
			}

			ComponentChanges += "\n\t" + InvokerComponent->GetPathName() + ": " + LexToString(LastInvokers[Index]) + " -> " + LexToString(Invokers[Index]);
		}
	}
	else
	{
		const TVoxelSet<TVoxelObjectPtr<const UVoxelNavigationInvokerComponent>> NewInvokerComponentsSet(NewInvokerComponents);
		const TVoxelSet<TVoxelObjectPtr<const UVoxelNavigationInvokerComponent>> LastInvokerComponentsSet(LastInvokerComponents);

		for (const TVoxelObjectPtr<const UVoxelNavigationInvokerComponent> InvokerComponent : NewInvokerComponentsSet.Difference(LastInvokerComponentsSet))
		{
			ComponentChanges += "\n\t" + InvokerComponent.GetPathName() + " added";
		}
		for (const TVoxelObjectPtr<const UVoxelNavigationInvokerComponent> InvokerComponent : LastInvokerComponentsSet.Difference(NewInvokerComponentsSet))
		{
			ComponentChanges += "\n\t" + InvokerComponent.GetPathName() + " removed";
		}
	}

	LastInvokerComponents = NewInvokerComponents;
#endif

	LastInvokers = Invokers;

	ensure(Future.IsComplete());

	Future = Voxel::AsyncTask(MakeWeakPtrLambda(this, [this, Invokers = MakeSharedCopy(MoveTemp(Invokers)), ComponentChanges = MoveTemp(ComponentChanges)]
	{
		VOXEL_SCOPE_COUNTER("FVoxelNavigationInvokerView");

		const TSharedRef<TVoxelSet<FIntVector>> NewChunks = MakeShared<TVoxelSet<FIntVector>>();

		if (!FVoxelUtilities::ComputeInvokerChunks(
			*NewChunks,
			MoveTemp(*Invokers),
			LocalToWorld,
			ChunkSize,
			1024 * 1024))
		{
			VOXEL_MESSAGE(Error, "More than 1M chunks generated by Navigation invoker for chunk size {1}, abording", ChunkSize);
		}

		{
			VOXEL_SCOPE_LOCK(CriticalSection);

			if (!Chunks_RequiresLock)
			{
				// Initialization, don't invalidate dependency
				Chunks_RequiresLock = NewChunks;
				return;
			}

			if (NewChunks->OrderIndependentEqual(*Chunks_RequiresLock))
			{
				return;
			}

			Chunks_RequiresLock = NewChunks;
		}

		FVoxelInvalidationScope Scope(ComponentChanges);
		Dependency->Invalidate();
	}));
}

///////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////

void FVoxelNavigationInvokerManager::LogInvokers()
{
	VOXEL_FUNCTION_COUNTER();
	checkVoxelSlow(IsInGameThread());

	const UWorld* World = GetWorld().Resolve();
	if (!ensure(World))
	{
		return;
	}

	LOG_VOXEL(Log, "Navigation invokers for %s:", *World->GetPathName());

	for (const UVoxelNavigationInvokerComponent* Invoker : InvokerComponents)
	{
		LOG_VOXEL(Log, "\tEnabled: %s Radius: %f %s", *LexToString(Invoker->bEnabled), Invoker->Radius, *Invoker->GetPathName());
	}
}

TSharedRef<FVoxelNavigationInvokerView> FVoxelNavigationInvokerManager::MakeView(
	const int32 ChunkSize,
	const FTransform& LocalToWorld)
{
	VOXEL_FUNCTION_COUNTER();
	check(IsInGameThread());

	const TSharedRef<FVoxelNavigationInvokerView> View = MakeShared<FVoxelNavigationInvokerView>(
		ChunkSize,
		LocalToWorld);

	// Ensure the view is up to date in the first query
	{
		FVoxelTaskScope Scope(*GVoxelGlobalTaskContext);
		View->Tick(InvokerComponents);
	}

	WeakViews.Add(View);
	return View;
}

///////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////

void FVoxelNavigationInvokerManager::Tick()
{
	VOXEL_FUNCTION_COUNTER();
	check(IsInGameThread());

	const double Time = FPlatformTime::Seconds();
	if (Time < LastTickTime + 0.05)
	{
		return;
	}
	LastTickTime = Time;

	for (auto It = WeakViews.CreateIterator(); It; ++It)
	{
		const TSharedPtr<FVoxelNavigationInvokerView> View = It->Pin();
		if (!View)
		{
			It.RemoveCurrent();
			continue;
		}

		View->Tick(InvokerComponents);
	}
}

void FVoxelNavigationInvokerManager::AddReferencedObjects(FReferenceCollector& Collector)
{
	VOXEL_FUNCTION_COUNTER();

	for (auto It = InvokerComponents.CreateIterator(); It; ++It)
	{
		TObjectPtr<UVoxelNavigationInvokerComponent> InvokerComponent = *It;
		Collector.AddReferencedObject(InvokerComponent);

		if (!ensure(InvokerComponent))
		{
			It.RemoveCurrent();
		}
	}
}

///////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////

UVoxelNavigationInvokerComponent::UVoxelNavigationInvokerComponent()
{
	// Make sure to disable collision so that GetComponentsBoundingBox ignores us
	BodyInstance.SetCollisionEnabled(ECollisionEnabled::NoCollision);
}

void UVoxelNavigationInvokerComponent::Serialize(FArchive& Ar)
{
	Super::Serialize(Ar);

	SerializeVoxelVersion(Ar);
}

void UVoxelNavigationInvokerComponent::OnRegister()
{
	Super::OnRegister();

	const UWorld* World = GetWorld();
	if (ensure(World))
	{
		ensure(!FVoxelNavigationInvokerManager::Get(World)->InvokerComponents.Contains(this));
		FVoxelNavigationInvokerManager::Get(World)->InvokerComponents.Add(this);
	}
}

void UVoxelNavigationInvokerComponent::OnUnregister()
{
	const UWorld* World = GetWorld();
	if (ensure(World))
	{
		FVoxelNavigationInvokerManager::Get(World)->InvokerComponents.Remove_Ensure(this);
	}

	Super::OnUnregister();
}

FPrimitiveSceneProxy* UVoxelNavigationInvokerComponent::CreateSceneProxy()
{
	if (UE_BUILD_SHIPPING)
	{
		return nullptr;
	}

	class FSceneProxy final : public FPrimitiveSceneProxy
	{
	public:
		const float Radius;

		explicit FSceneProxy(const UVoxelNavigationInvokerComponent* Component)
			: FPrimitiveSceneProxy(Component)
			, Radius(Component->Radius)
		{
		}

		virtual void GetDynamicMeshElements(
			const TArray<const FSceneView*>& Views,
			const FSceneViewFamily& ViewFamily,
			const uint32 VisibilityMap,
			FMeshElementCollector& Collector) const override
		{
			VOXEL_FUNCTION_COUNTER();

			for (int32 ViewIndex = 0; ViewIndex < Views.Num(); ViewIndex++)
			{
				if (!(VisibilityMap & (1 << ViewIndex)))
				{
					continue;
				}

				FPrimitiveDrawInterface* PDI = Collector.GetPDI(ViewIndex);
				const FSceneView* View = Views[ViewIndex];
				const FMatrix LocalToWorld = GetLocalToWorld();

				const FLinearColor Color = GetViewSelectionColor(
					FColor::White,
					*View,
					IsSelected(),
					IsHovered(),
					false,
					IsIndividuallySelected());

				DrawWireSphere(
					PDI,
					LocalToWorld.GetOrigin(),
					Color,
					Radius,
					64,
					SDPG_World);
			}
		}
		virtual FPrimitiveViewRelevance GetViewRelevance(const FSceneView* View) const override
		{
			FPrimitiveViewRelevance Result;
			Result.bDrawRelevance = (!View->Family->EngineShowFlags.Game && IsSelected()) || GVoxelShowNavigationInvokers;
			Result.bDynamicRelevance = true;
			return Result;
		}
		virtual SIZE_T GetTypeHash() const override
		{
			static size_t UniquePointer;
			return reinterpret_cast<size_t>(&UniquePointer);
		}
		virtual uint32 GetMemoryFootprint() const override
		{
			return sizeof(*this) + GetAllocatedSize();
		}
	};
	return new FSceneProxy(this);
}

FBoxSphereBounds UVoxelNavigationInvokerComponent::CalcBounds(const FTransform& LocalToWorld) const
{
	return FBoxSphereBounds(FVector::ZeroVector, FVector(Radius), Radius).TransformBy(LocalToWorld);
}