// Copyright Voxel Plugin SAS. All Rights Reserved.

#include "K2Node_MakeVoxelPinValue.h"
#include "VoxelPinTypeSet.h"
#include "Kismet2/BlueprintEditorUtils.h"
#include "VoxelPinValueBlueprintLibrary.h"

UK2Node_MakeVoxelPinValue::UK2Node_MakeVoxelPinValue()
{
	FunctionReference.SetExternalMember(
		GET_FUNCTION_NAME_CHECKED(UVoxelPinValueBlueprintLibrary, K2_MakeVoxelPinValue),
		UVoxelPinValueBlueprintLibrary::StaticClass());

	CachedType = FVoxelPinType::MakeWildcard();
}

///////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////

void UK2Node_MakeVoxelPinValue::GetNodeContextMenuActions(UToolMenu* Menu, UGraphNodeContextMenuContext* Context) const
{
	Super::GetNodeContextMenuActions(Menu, Context);

	if (!Context->Pin ||
		!IsPinWildcard(*Context->Pin))
	{
		return;
	}

	AddConvertPinContextAction(Menu, Context, FVoxelPinTypeSet::AllUniforms());
}

///////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////

void UK2Node_MakeVoxelPinValue::NotifyPinConnectionListChanged(UEdGraphPin* Pin)
{
	FEdGraphPinType OldPinType = Pin->PinType;

	Super::NotifyPinConnectionListChanged(Pin);

	if (!IsPinWildcard(*Pin))
	{
		return;
	}

	FEdGraphPinType TargetType = OldPinType;
	if (Pin->LinkedTo.Num() == 1)
	{
		UEdGraphPin* LinkedPin = Pin->LinkedTo[0];
		if (!ensure(LinkedPin))
		{
			return;
		}

		TargetType = LinkedPin->PinType;
	}

	const FVoxelPinType NewType = FVoxelPinType::MakeFromK2(TargetType);
	if (!NewType.IsValid())
	{
		CachedType = {};
		return;
	}

	if (TargetType == OldPinType)
	{
		if (Pin->LinkedTo.Num() == 0 &&
			Pin->PinType != TargetType)
		{
			ReconstructNode();
		}
		return;
	}

	if (CachedType == NewType)
	{
		return;
	}

	if (!ensure(!NewType.IsWildcard()))
	{
		return;
	}

	const FVoxelTransaction Transaction(this, "Change Type");
	CachedType = NewType;

	ReconstructNode();

	// Let the graph know to refresh
	GetGraph()->NotifyGraphChanged();

	UBlueprint* Blueprint = GetBlueprint();
	if (!Blueprint->bBeingCompiled)
	{
		FBlueprintEditorUtils::MarkBlueprintAsModified(Blueprint);
		Blueprint->BroadcastChanged();
	}
}

void UK2Node_MakeVoxelPinValue::PostReconstructNode()
{
	Super::PostReconstructNode();

	const UEdGraphSchema_K2* Schema = GetDefault<UEdGraphSchema_K2>();
	if (UEdGraphPin* ExposedValuePin = FindPin(FName("Value")))
	{
		ExposedValuePin->PinType = CachedType.GetEdGraphPinType_K2();
		if (ExposedValuePin->DoesDefaultValueMatchAutogenerated())
		{
			Schema->ResetPinToAutogeneratedDefaultValue(ExposedValuePin, false);
		}
	}
}

bool UK2Node_MakeVoxelPinValue::IsConnectionDisallowed(const UEdGraphPin* MyPin, const UEdGraphPin* OtherPin, FString& OutReason) const
{
	if (!IsPinWildcard(*MyPin))
	{
		return Super::IsConnectionDisallowed(MyPin, OtherPin, OutReason);
	}

	if (!CanAutoConvert(*MyPin, *OtherPin, OutReason))
	{
		return true;
	}

	return Super::IsConnectionDisallowed(MyPin, OtherPin, OutReason);
}

///////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////

bool UK2Node_MakeVoxelPinValue::IsPinWildcard(const UEdGraphPin& Pin) const
{
	return Pin.PinName == "Value";
}

void UK2Node_MakeVoxelPinValue::OnPinTypeChange(UEdGraphPin& Pin, const FVoxelPinType& NewType)
{
	if (CachedType == NewType)
	{
		return;
	}

	const FVoxelTransaction Transaction(this, "Change Type");

	const bool bSameType = CachedType == NewType;
	CachedType = NewType;

	if (!bSameType)
	{
		if (Pin.LinkedTo.Num() > 0 ||
			!Pin.DoesDefaultValueMatchAutogenerated())
		{
			if (Pin.PinFriendlyName.IsEmpty())
			{
				Pin.PinFriendlyName = FText::FromName(Pin.PinName);
			}

			Pin.PinName = CreateUniquePinName(Pin.PinName);
		}

		ReconstructNode();
	}

	// Let the graph know to refresh
	GetGraph()->NotifyGraphChanged();

	UBlueprint* Blueprint = GetBlueprint();
	if (!Blueprint->bBeingCompiled)
	{
		FBlueprintEditorUtils::MarkBlueprintAsModified(Blueprint);
		Blueprint->BroadcastChanged();
	}
}